version: '3'

services:
    app:
        build: .
        ports: 
            - '${PORT}:80'
        environment:
            TOKEN: ${TOKEN}
            USE_DB: 'true'
            DB_HOST: ${DB_HOST}
            DB_DBNAME: ${DB_DBNAME}
            CRONTAB: ${CRONTAB}
            WORKER_NAME: ${WORKER_NAME}
        restart: always