version: '3'

services:
    app:
        build: .
        environment:
            TOKEN: ${TOKEN}
            USE_DB: 'true'
            DB_HOST: ${DB_HOST}
            DB_DBNAME: ${DB_DBNAME}
            CRONTAB: '*/10 * * * * *'
            WORKER_NAME: ${WORKER_NAME}